markdown: kramdown
permalink: /blog/:year/:month/:day/:title
pages_dir: /pages
high_res_image: "/assets/images/demonic_tiger_oil_canvas.q75.webp"
low_res_image: "/assets/images/demonic_tiger_oil_canvas.q0.webp"
exclude:
  - CNAME
  - Dockerfile
  - Makefile
  - README.md
